### PR TITLE
Bump to 2.8 cdap

### PR DESCRIPTION
**Pull request by gokulavasan**

### CODE REVIEW

**Comment by anwar6953** [comment]
I think before you bumb to 2.8, you should merge develop to the 2.7 release branch. there have been changes to develop since then.

**Comment by poornachandra** [comment]
We don't merge develop into release branch.

**Comment by gokulavasan** [comment]
Checked with @anwar6953 . The changes he wanted was already in the release branch. We just need to verify if this 2.8.0-SNAPSHOT works with develop.

**Comment by anwar6953** [comment]
yea, LGTM

**Comment by gokulavasan** [comment]
@sreevatsanraman Please review.

**Comment by poornachandra** [comment]
LGTM

**Pull request merged**
